apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.rootPassword | quote }}

