apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | required "database.url is required" }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | required "minio.accessKey is required" }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | required "minio.secretKey is required" }}

